# Generated by Gemini
# Use a slim Python image for a smaller footprint
FROM python:3.11-slim-bookworm

# Install uv for fast dependency management
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install system dependencies required by Doxygen and its diagram features
RUN apt-get update && apt-get install -y --no-install-recommends \
    doxygen \
    graphviz \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the project files into the container
# Use .dockerignore to avoid copying unnecessary files like .venv and .git
COPY . .

# Install Python dependencies using uv
RUN uv sync

# Expose no ports as MCP servers typically communicate over stdio

# The entrypoint runs the MCP server via uv
# This ensures it runs within the synchronized environment
ENTRYPOINT ["uv", "run", "doxygen-mcp"]
